# Generated by Django 4.2.7 on 2023-11-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='graudedificuldade',
            field=models.CharField(choices=[('F', 'Facil'), ('M', 'Moderado'), ('D', 'Dificil')], max_length=10),
        ),
    ]
